name: Cypress test in GitHub Action
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress test cases
        uses: cypress-io/github-action@v2
        with:
          start: npm start

